
development:
  adapter: postgresql
  encoding: utf8
  database: huffpo_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: huffpo_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: huffpo_production
  pool: 5
